format_version: 10                # pipeline version from gocd, based on this options would vary 
pipelines: 
  test: 
    group: App-Deployments
    label_template: "${COUNT}"
    materials:
      mysql-code:
        git: https://github.com/B58-CloudDevOps/ansible.git
        branch: main
        auto_update: true 
        shallow_clone: true
        display_order: -1
        lock_behavior: none
    stages:
      - dev:
          fetch_materials: true 
          keep_artifacts: false
          clean_workspace: false 
          jobs:
            Build:
              tasks:
                - exec:
                    command: ls 
                    arguments:
                    - -ltr

      - qa:
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            Build:
              tasks:
                - exec:
                    run_if: passed
                    command: ls
                    arguments:
                    - -ltr 

      - stage:
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            Build:
              tasks:
                - exec:
                    run_if: passed
                    command: ls 
                    arguments:
                    - -ltr 

      - prod:
          fetch_materials: true 
          keep_artifacts: false
          clean_workspace: false 
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            Build:
              tasks:
                - exec:
                    run_if: passed
                    command: ls 
                    arguments:
                    - -ltr 