format_version: 10                
pipelines: 
  tools-infra-create:                                            
    group: Terraform
    label_template: "${COUNT}"
    materials:
      mysql-code:
        git: https://github.com/B58-CloudDevOps/tools-automation.git
        branch: main
        auto_update: true 
        shallow_clone: true
        display_order: -1
        lock_behavior: none
    secure_variables:
        SSH_PSW: "AES:2OIP4os11Nz8gJ+jtzoUMg==:9RKApCuI7ST7rHEU5UsKuA=="
    stages:                                       
      - infra:                                       
          fetch_materials: true 
          keep_artifacts: false
          clean_workspace: false
          jobs:
            terraform:
              tasks:
                - exec: { command: bash, arguments: ["init.sh"] }
   

